---
title: "Shooting Occurrences Increased Across the City of Toronto between 2014 and 2019"
author: "Talia Fabregas"
date: "January 21, 2024"
format: pdf
editor: visual
---

## Abstract

Shooting data

## Contents

1.  Introduction

2.  Data

    1.  Data Collection

    2.  Data Processing

    3.  Ethical Considerations

3.  Conclusions

4.  References

5.  References

## Introduction

## Data

```{r}
#| include: false
#| warning: false
#| message: false
library(tidyverse)
library(opendatatoronto)
library(janitor)
library(dplyr)
library(ggplot2)

# loading the cleaned data
shooting_data <- read_csv(here::here("outputs/data/toronto_shooting_data.csv"))
shooting_data


  
```

## 

```{r}
#| label: fig-yearlytotalshootings
#| fig-cap: Total Number of Shooting Occurrences Acoross Toronto, 2014-2019
#| echo: false
#| warning: false
#| message: false
yearly_totals <- shooting_data |>
  group_by(occurred_year) |>
  summarise(total = sum(count))

yearly_totals_df <- data.frame(
  Year = yearly_totals$occurred_year,
  Total = yearly_totals$total
)

ggplot(yearly_totals_df, aes(x=Year, y=Total)) +
  geom_bar(stat="identity", fill="#f36767", width=0.8) +
  geom_line(size=1, color="blue", ) +
  scale_x_continuous(breaks = seq(min(yearly_totals_df$Year), max(yearly_totals_df$Year), by = 1))
```

```{r}
#| label: fig-amrushdelays
#| fig-cap: Morning Rush Hour Delays, by Day
#| echo: false
#| warning: false
#| message: false

# weekdays <- streetcar_data |>
#   filter(day == "Monday" | day == "Tuesday" | day == "Wednesday" |
#            day == "Thursday" | day == "Friday") 
# amrush <- weekdays |>
#   filter(am_rush == 1) |>
#   group_by(day) |>
#   summarize(am_delays = n())
# 
# pmrush <- weekdays |>
#   filter(pm_rush == 1) |>
#   group_by(day) |>
#   summarize(pm_delays = n())

area_totals <- shooting_data |>
  group_by(geo_division, occurred_year) |>
  summarise(total = sum(count))

ggplot(area_totals, aes(x=geo_division, y=total, fill=geo_division)) +
    geom_bar(stat="identity") +
  theme(axis.text.x = element_blank()) +
    facet_wrap(~occurred_year)

```

```{r}
#| label: fig-yearlytotalsbydivision
#| fig-cap: Annual Shooting Occurrences 2014-2019, by Toronto Police Division
#| echo: false
#| warning: false
#| message: false

ggplot(area_totals, aes(x=occurred_year, y=total)) +
    geom_bar(stat="identity", fill="#f36767", width=0.8) +
  geom_line(color="blue") +
  scale_x_continuous(breaks = seq(min(yearly_totals_df$Year), max(yearly_totals_df$Year), by = 1)) +
  theme(axis.text = element_text(size = 5)) +
  facet_wrap(~geo_division)


```

## Conclusions

## References
